# ✅ dev 프로필에서만 읽힘 (SPRING_PROFILES_ACTIVE=dev)
client.url: http://localhost:5173

spring:
  security:
    oauth2:
      client:
        registration:
          google:                             # /oauth2/authorization/google 의 {registrationId}
            client-id: 64315682409-s36kfmklqmlii2v7lspgrd054nl881ab.apps.googleusercontent.com        # 환경변수로 주입
            client-secret: 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  # 환경변수로 주입
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: email, profile   # ← OIDC 유지


          kakao:
            client-id: 9f3745f3eb293f2cd6ede1debda8d878        # 콘솔의 "REST API 키"
            client-secret: LWuDJN7DlCOXxsLneY1ci80H80DALC0n
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: account_email
            client-name: Kakao

          naver:
            client-id: m53pWg9RYjqh2F8qbxvc         # 발급받은 Client ID
            client-secret: 8u4wykUfey # 발급받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email,profile_image
            client-name: Naver

        provider:
          google:
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:         https://kauth.kakao.com/oauth/token
            user-info-uri:     https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri:         https://nid.naver.com/oauth2.0/token
            user-info-uri:     https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework.security: INFO        # 필요시 DEBUG로

jwt:
  secret: "2DeCoyOLo/Rb6DfOYECvzx4zjAXPh7gVY/bxpH4YpF0=" # 최소 256bit 이상 문자열
  access-exp-seconds: 1800        # 30분
  refresh-exp-seconds: 1209600    # 14일
